const Pool = require('pg').Pool;

// this code will work and a table will be created if you have already created the "testWad" database.
const pool = new Pool({
    user: "postgres",
    password: "sql", // Enter your password here
    database: "test", //Try to use the same name for your database
    host: "localhost",
    port: "5432"
});


const execute = async(query) => {
    try {
        await pool.connect(); // gets connection
        await pool.query(query); // sends queries
        return true;
    } catch (error) {
        console.error(error.stack);
        return false;
    }
};

// A simple query that creates a table in our database
// Note that the "SERIAL"  pseudo-type that is used after the "id" is used to create a sequence object,
// and set the next value generated by the sequence as the default value for the column
const createTblQuery = `
    CREATE TABLE IF NOT EXISTS "posttable" (
	    "id" SERIAL PRIMARY KEY,         
	    "title" VARCHAR(200) NOT NULL,
	    "body" VARCHAR(200) NOT NULL,
        "isliked" BOOLEAN 
    );`;

const createUserTabelQuery = `
        CREATE TABLE IF NOT EXISTS "userstable" (
            "id" SERIAL PRIMARY KEY,
            "email" VARCHAR(200) NOT NULL,
            "password" VARCHAR(200) NOT NULL
        );`;



// A function to execute the previous query   
execute(createTblQuery).then(result => {
    if (result) {
        console.log('If does not exists, create the "posttable" table');
    }
});

execute(createUserTabelQuery).then(result =>{
    if(result){
        console.log("Users table created")
    }
})



module.exports = pool;